from pathlib import Path
import logging

from openpyxl import load_workbook
from openpyxl.worksheet.worksheet import Worksheet

from src.core.exceptions import WorkbookError
from src.core.models import ComplianceFlagModel
from src.utils.file_utils import ensure_parent

# ExcelWriter is a simple writer for .xlsx files that writes the compliance flags generated by the LLM into the output sheets for each resident.
# It is used to write the compliance flags generated by the LLM into the output sheets for
# each resident, which can then be reviewed by the care team to identify any documentation gaps and take corrective actions.
# The writer appends the flags into the first blank row of the output sheet to preserve the workbook template and formatting, and includes a detailed explanation for each flag to provide context and guidance for remediation.
#  The writer also includes error handling to ensure that the output sheet exists in the workbook, and raises a WorkbookError if the sheet is missing.
# This helps ensure that the compliance flags are recorded accurately and can be easily reviewed by the care team.


class ExcelWriter:
    def __init__(self, output_path: Path) -> None:
        self.output_path = output_path
        self.logger = logging.getLogger("processx")

    def open_workbook(self, source_path: Path):
        if not source_path.exists():
            raise WorkbookError(f"Workbook not found: {source_path}")
        return load_workbook(source_path)

    def write_flags(
        self, workbook, sheet_name: str, flags: list[ComplianceFlagModel]
    ) -> None:
        if sheet_name not in workbook.sheetnames:
            raise WorkbookError(f"Missing output sheet: {sheet_name}")
        worksheet: Worksheet = workbook[sheet_name]
        # We append into the first blank row so the workbook template and formatting remain intact.
        start_row = self._next_empty_row(worksheet)
        for index, flag in enumerate(flags, start=start_row):
            worksheet[f"A{index}"] = flag.day_label
            worksheet[f"B{index}"] = flag.severity.value
            worksheet[f"C{index}"] = flag.field
            worksheet[f"D{index}"] = self._build_explanation(flag)
        self.logger.info(
            "workbook_write",
            extra={"sheet": sheet_name, "flags_written": len(flags)},
        )

    def save(self, workbook) -> None:
        ensure_parent(self.output_path)
        workbook.save(self.output_path)
        self.logger.info("workbook_saved", extra={"path": str(self.output_path)})

    def _next_empty_row(self, worksheet: Worksheet) -> int:
        row = 4
        while any(
            worksheet[f"{column}{row}"].value not in (None, "") for column in "ABCD"
        ):
            row += 1
        return row

    def _build_explanation(self, flag: ComplianceFlagModel) -> str:
        return (
            f"Policy Rule: {flag.policy_rule_id}. "
            f"Trigger Condition: {flag.trigger_condition}. "
            f"Evidence Found: {flag.evidence_found[:220]}. "
            f"Missing Requirement: {flag.missing_requirement}. "
            f"Recommendation: {flag.recommendation}"
        )
